server:
  port: 9011
spring:
  application:
    name: verynavi-manager #后台管理的微服务网关
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer‐ip‐address: true
jwt:
  config:
    key: verynavi
zuul:
  routes:
    verynavi‐gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: verynavi‐gathering #指定Eureka注册中心中的服务id
    verynavi‐article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: verynavi‐article #指定Eureka注册中心中的服务id
    verynavi‐base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: verynavi‐base #指定Eureka注册中心中的服务id
    verynavi‐friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: verynavi‐friend #指定Eureka注册中心中的服务id
    verynavi‐qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: verynavi‐qa #指定Eureka注册中心中的服务id
    verynavi‐recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: verynavi‐recruit #指定Eureka注册中心中的服务id
    verynavi‐spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: verynavi‐spit #指定Eureka注册中心中的服务id
    verynavi‐user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: verynavi‐user #指定Eureka注册中心中的服务id
