server:
  port: 9007
spring:
  application:
    name: verynavi-search
  data:
    elasticsearch:
      #elasticsearch 给java开的后门，  9200通常是任何编程语言都可以去连接
      cluster-nodes: 10.211.55.8:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
