server:
  port: 9008
spring:
  application:
    name: verynavi-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.8:3306/tensquare_user?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 10.211.55.8
  rabbitmq:
    host: 10.211.55.8
