server:
  port: 12000
spring:
  application:
    name: verynavi-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/geekerstar/verynavi_dev.git
  rabbitqm:
     host: 10.211.55.8
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
