server:
  port: 9004
spring:
  application:
    name: verynavi-article #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.8:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 10.211.55.8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
