server:
  port: 9005
spring:
  application:
    name: verynavi-gathering #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.8:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: root
  redis:
    host: 10.211.55.8
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
