server:
  port: 9005
spring:
  application:
    name: verynavi-gathering #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.8:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
